
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJH9fs7CB7faiW2XHxFLf5dbzeUaOPi44',
    appId: '1:72924983874:web:6e0cdf676e25c04bebf3db',
    messagingSenderId: '72924983874',
    projectId: 'habitar-c1f00',
    authDomain: 'habitar-c1f00.firebaseapp.com',
    storageBucket: 'habitar-c1f00.firebasestorage.app',
    measurementId: 'G-WDRCK76W8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkaoPYbm2gADXoBgbG_6nWYDhbXgfsTuQ',
    appId: '1:72924983874:android:7ccc3030d33627daebf3db',
    messagingSenderId: '72924983874',
    projectId: 'habitar-c1f00',
    storageBucket: 'habitar-c1f00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSytLWV5HInbuBtBIALe87rh2m_OTmec',
    appId: '1:72924983874:ios:c87349b811042878ebf3db',
    messagingSenderId: '72924983874',
    projectId: 'habitar-c1f00',
    storageBucket: 'habitar-c1f00.firebasestorage.app',
    iosBundleId: 'com.habitar.habitar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSytLWV5HInbuBtBIALe87rh2m_OTmec',
    appId: '1:72924983874:ios:c87349b811042878ebf3db',
    messagingSenderId: '72924983874',
    projectId: 'habitar-c1f00',
    storageBucket: 'habitar-c1f00.firebasestorage.app',
    iosBundleId: 'com.habitar.habitar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJH9fs7CB7faiW2XHxFLf5dbzeUaOPi44',
    appId: '1:72924983874:web:c164b164a0209e48ebf3db',
    messagingSenderId: '72924983874',
    projectId: 'habitar-c1f00',
    authDomain: 'habitar-c1f00.firebaseapp.com',
    storageBucket: 'habitar-c1f00.firebasestorage.app',
    measurementId: 'G-YYKQD0MHR4',
  );

}